spring.application.name=Sharesphere

#URL
app.base-url=http://localhost:8080
app.front-url=bacayuk://auth
# Frontend path mapping
app.front-url-path.magic-login=magic-login
app.front-url-path.reset-password=reset-password

firebase.service-account.path=${FIREBASE_SERVICE_ACCOUNT}


#web static
app.web.base-url=https://information-web.onrender.com


#database config
spring.datasource.url=jdbc:postgresql://localhost:5432/sharesphere
spring.datasource.username=your_username
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.hibernate.ddl-auto=update


#Cloud stroage AWS S3
aws.s3.bucket=sharesphere1
aws.s3.region=ap-southeast-1
aws.s3.expiry=2
aws.s3.public-url-template=https://%s.s3.%s.amazonaws.com/%s

#secret
jwt.secret=${JWT_SECRET}

#konfigurasi masa berlaku email
jwt.email.expMinutes=0
jwt.email.expHours=0
jwt.email.expDays=7

# Konfigurasi masa berlaku access-token
jwt.access.expMinutes=30
jwt.access.expHours=0
jwt.access.expDays=0


# Konfigurasi masa berlaku one time token
jwt.onetime.expMinutes=5
jwt.onetime.expHours=0
jwt.onetime.expDays=0


# Konfigurasi masa berlaku refresh-token
jwt.refresh.expMinutes=0
jwt.refresh.expHours=30
jwt.refresh.expDays=0


# konfigurasi masa berlaku reset password
jwt.password-reset.exp-minutes= 0
jwt.access.exp-hours= 0
jwt.password-reset.exp-days= 7 


# Nearby Search Configuration
app.nearby-search.default-radius=5.0
app.nearby-search.sparse-area-radius=25.0
app.nearby-search.max-radius=50.0
app.nearby-search.target-results=20
app.nearby-search.min-results-threshold=8
app.nearby-search.max-results=50
app.nearby-search.pagination-multiplier=1.5


#Environment
spring.profiles.active=dev

logging.level.org.springframework.security=DEBUG
#Email
sendgrid.api.key=${SENDGRID_API_KEY}

sendgrid.template.verification=${TEMPLATE_VERIFICATION}
sendgrid.template.reset-password=${TEMPLATE_RESET_PASSWORD}

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
