spring.application.name=Sharesphere

# Base URL Render
app.base-url=https://sharesphere.onrender.com

app.front-url=bacayuk://auth
# Frontend path mapping
app.front-url-path.magic-login=magic_login
app.front-url-path.reset-password=reset_password

firebase.service-account.path=${FIREBASE_SERVICE_ACCOUNT}

#web static
app.web.base-url=https://information-web.onrender.com

# PostgreSQL Render
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=your_username
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=DEBUG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.spatial.enabled=true
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

jwt.secret=${JWT_SECRET}


#konfigurasi masa berlaku email
jwt.email.expMinutes=0
jwt.email.expHours=0
jwt.email.expDays=7

# Konfigurasi masa berlaku access-token
jwt.access.expMinutes=30
jwt.access.expHours=0
jwt.access.expDays=0

#Cloud stroage AWS S3
aws.s3.bucket=sharesphere1
aws.s3.region=ap-southeast-1
aws.s3.expiry=2
aws.s3.public-url-template=https://%s.s3.%s.amazonaws.com/%s


# Konfigurasi masa berlaku one time token
jwt.onetime.expMinutes=5
jwt.onetime.expHours=0
jwt.onetime.expDays=0

# Konfigurasi masa berlaku refresh-token
jwt.refresh.expMinutes=0
jwt.refresh.expHours=0
jwt.refresh.expDays=7

sendgrid.api.key=${SENDGRID_API_KEY}

sendgrid.template.verification=${TEMPLATE_VERIFICATION}
sendgrid.template.reset-password=${TEMPLATE_RESET_PASSWORD}


# Nearby Search Configuration
app.nearby-search.default-radius=5.0
app.nearby-search.sparse-area-radius=25.0
app.nearby-search.max-radius=50.0
app.nearby-search.target-results=20
app.nearby-search.min-results-threshold=8
app.nearby-search.max-results=50
app.nearby-search.pagination-multiplier=1.5

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE